spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    jwt:
      key: sadasfgwq
      expire: 7
    filter:
      order: -100
  redis:
    blockTime: 60
  rabbitmq:
    addresses: 192.168.0.220
    username: root
    password: root
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
  mail:
    host: smtp.163.com
    username: 18978935701@163.com
    password: UZMHHWEOEPRAALYK
  datasource:
    url: jdbc:mysql://localhost:3306/bookmall
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /static/**
file:
  upload:
    pathHead: D://images/head
    pathCover: D://images/cover
    relative: /images/**
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
